name: test

on:
  # Manual trigger for the workflow
  workflow_dispatch:

  # Trigger on any push to the master branch
  push:
    branches:
      - "master"

jobs:
  # First workflow call
  workflow_call:
    uses: vivek7252/ci-cd-1/.github/workflows/ci.yml@master
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

  # Second workflow call
  workflow_call_2:
    uses: vivek7252/my-repo/.github/workflows/another-pipeline.yaml@main
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
